replicaCount: 1

image:
  initContainer: alpine:3.17.3
  repository: ghcr.io/memenow/stable-diffusion-webui
  tag: 1.6.0-rc

pvc:
  dataset:
    storage: 80Gi
  model:
    storage: 150Gi

service:
  type: NodePort